#!/bin/bash

PATH=/bin:/usr/bin:/usr/local/bin

DOCKER_VERSION=$(docker version)
DOCKER_INFO=$(docker info)

STORAGE_DRIVER=$(echo "$DOCKER_INFO" | grep Storage\ Driver | awk '{print $NF}')
VERSION=$(echo "$DOCKER_VERSION" | grep Version | head -n 1  | awk '{print $2}')

cat <<EOF
Docker $VERSION is running using the '$STORAGE_DRIVER' storage driver.
EOF
